PROJECT = websocket

DEPS = cowboy jiffy
dep_cowboy_commit = 2.9.0
dep_jiffy_commit = master

DEP_PLUGINS = cowboy
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0
BUILD_DEPS += relx


include erlang.mk

